<div>
	<div>
		<div id="content-header"><label>SEARCH RESULTS</label><input type="button" value="DELETE" /></div>
		<div id="registered_users">
			<table>
				<tr>
					<th></th>
					<th>ID</th>
					<th>Username</th>
					<th>E-mail</th>
					<th>Plan</th>
					<th>Actions</th>
				</tr>
				<tr>
					<td><input type="checkbox" /></td>
					<td>222</td>
					<td>rizza</td>
					<td>E-rizza</td>
					<td>rizza</td>
					<td><a href="users/user-listing/edit">EDIT</a><input type="button" name="btnAction" value="CHANGE PLAN"><input type="button" name="btnAction" value="LOGIN"></td>
				</tr>
			</table>
		</div>
	</div>
</div>