<div class="popupDialog product_dialog addArticle_popUp">
<h3><img src="/Project/Design/2_Enterprise/Applications/Products/Main_App_Layout/images/plus.png" />Create New Entry</h3>
	<div class="subCategory_entity">
		<form method="POST" action="/<?=routes::getInstance()->getCurrentTopLevelURLName()?>/article/add">
			<div class="mBxl">
				<strong>Title</strong>
				<input class="validate[required,maxlength[45]] fright subCategory_entityTitle" type="text" name="title" maxlength="45">
			</div>
			<div class="mBxl">
				<strong>Url</strong><input class="fright subCategory_entityDescription" name="article_url" disabled="disabled"/>
			</div>
			<div id="button_container" class="fright mRs mBs">
				<input name="article_type" type="hidden" value="<?=routes::getInstance()->getCurrentTopLevelPageID();?>">
				<input name="category_id" type="hidden" value="">
				<input name="subcategory_id" type="hidden" value="">
				<input type="submit" class="sprite fleft mRs mTs" name="add_article" value=" ">
				<span class="sprite mTs fleft pointer cancel" title="cancel"></span>
			</div>
		</form>
	</div>
</div>