<?
	$increment = 1;
	$pdf_used = array();
?>
<table>
	<tbody>
		<tr>
			<?php foreach($this->_get('array_of_pdfs') as $pdf):?>
				<?if($increment % 4 == 1 && $increment != 1):?>
					</tr><tr>
				<?endif; ?>
				<td class="fleft" data-fileType="<?=pathinfo($pdf->__get('filename'), PATHINFO_EXTENSION);?>">
					<?php if($pdf->__get('is_used') == 1):?>
						<label class="clearfix">
							<div class="pdfName clearfix">
								<p><?=$pdf->__get('filename');?></p>
							</div>
						<p><input type="checkbox" name="pdf" checked value="<?=$pdf->__get('pdf_id');?>"/><span class="inUse"></span></p>
						</label>
						<?php else:?>
						<label class="clearfix">
							<div class="pdfName"><p><?=$pdf->__get('filename');?></p></div>
							<p><input type="checkbox"  name="pdf" value="<?=$pdf->__get('pdf_id');?>"/><span class="notUsed"></span></p>
						</label>
						<span id="delete" data-filename="<?=$pdf->__get('path');?>" data-id="<?=$pdf->__get('pdf_id');?>">Delete File</span>
						<?php endif?>
				</td>
			<?php endforeach?>
		</tr>	
	</tbody>
</table>		
%%DELETE_DIALOG%%