<div id="upload-dialog" class="posRel newFile popupDialog">
	<h3><img src="/Project/Design/2_Enterprise/Applications/Products/Main_App_Layout/images/plus.png">Upload New PDF</h3>
	<form id="uploadFile" method="POST" action="/files/pdf/add" enctype="multipart/form-data">
		<input type="file" name="file" class="required trueInputFile">
		<div class="fakeInputFile sprite"><div id="fakeInputFile-text"><span></span></div></div>
		<div class="fright mBm">
			<input class="sprite fleft mRxs mTs" type="submit" name="upload" value="Upload File">
			<span class="sprite cancelUpload pointer mTs fleft" title="cancel"></span>
		</div>
	</form>
</div>