%%BANNER%%
<div id="<?=routes::getInstance()->getCurrentTopLevelPageID();?>_content_wrapper">
	<div class="bottomSection clearfix">
		<a id="back" href="/about-us">&lt; Back</a>
		<h1>Our <?=strtolower(routes::getInstance()->getCurrentSubLevelLinkText())?></h1>
		<?=$this->displayImage(0)?>
		<div id="content" class="clearfix pAxl mBxxl mTm">
			<?=$this->displayElement('page_content_editor')?>
		</div>
	</div>
</div>