<div id="<?=routes::getInstance()->getCurrentTopLevelPageID();?>_content_wrapper" class="pVl">
	<div class="topSection clearfix align_c">
		<?=$this->displayElement('page_content_editor'); ?>
	</div>
	<div class="bottomSection clearfix">
		<?$image_path = $this->getArrayofImages()?>
		<div class="clearfix">
			<a href="/about-us/welcome" class="aboutAvior grayscale">
				<span class="topPointer show">WELCOME</span>
				<span class="imageContainer" style="background-image: url('<?=$image_path[0]?>')"></span>
			</a>
			<a href="/about-us/services" class="aboutAvior grayscale">
				<span class="topPointer show">SERVICES</span>
				<span class="imageContainer" style="background-image: url('<?=$image_path[1]?>')"></span>
			</a>
			<a href="/about-us/fleet-manned" class="aboutAvior grayscale">
				<span class="topPointer show">FLEET MANNED</span>
				<span class="imageContainer" style="background-image: url('<?=$image_path[2]?>')"></span>
			</a>
			<a href="/about-us/accreditations" class="aboutAvior grayscale last">
				<span class="topPointer show">ACCREDITATIONS</span>
				<span class="imageContainer" style="background-image: url('<?=$image_path[3]?>')"></span>
			</a>
		</div>
		<div class="clearfix mTxl">
			<a href="/about-us/company-profile" class="aboutAvior grayscale">
				<span class="topPointer show">COMPANY PROFILE</span>
				<span class="imageContainer" style="background-image: url('<?=$image_path[4]?>')"></span>
			</a>
			<a href="/about-us/quality-policy" class="aboutAvior grayscale">
				<span class="topPointer show">QUALITY POLICY</span>
				<span class="imageContainer" style="background-image: url('<?=$image_path[5]?>')"></span>
			</a>
			<a href="/about-us/business-ethics" class="aboutAvior grayscale">
				<span class="topPointer show">BUSINESS ETHICS</span>
				<span class="imageContainer" style="background-image: url('<?=$image_path[6]?>')"></span>
			</a>
			<a href="/about-us/mlc-2006" class="aboutAvior grayscale last">
				<span class="topPointer show">MLC-2006</span>
				<span class="imageContainer" style="background-image: url('<?=$image_path[7]?>')"></span>
			</a>
		</div>
	</div>
</div>