<div id="<?=routes::getInstance()->getCurrentTopLevelPageID();?>_content_wrapper" class="pVl">
	<div class="topSection clearfix align_c">
		<?=$this->displayElement('page_content_editor'); ?>
	</div>
	<div class="bottomSection clearfix">
		<div class="clearfix">
			<a href="/about-us/welcome" class="aboutAvior grayscale">
				<span class="topPointer show">WELCOME</span>
				<?=$this->displayImage('0'); ?>
			</a>
			<a href="/about-us/services" class="aboutAvior grayscale">
				<span class="topPointer show">SERVICES</span>
				<?=$this->displayImage('1'); ?>
			</a>
			<a href="/about-us/fleet-managed" class="aboutAvior grayscale">
				<span class="topPointer show">FLEET MANAGED</span>
				<?=$this->displayImage('2'); ?>
			</a>
			<a href="/about-us/accreditations" class="aboutAvior grayscale last">
				<span class="topPointer show">ACCREDITATIONS</span>
				<?=$this->displayImage('3'); ?>
			</a>
		</div>
		<div class="clearfix mTxl">
			<a href="/about-us/company-profile" class="aboutAvior grayscale">
				<span class="topPointer show">COMPANY PROFILE</span>
				<?=$this->displayImage('4'); ?>
			</a>
			<a href="/about-us/quality-policy" class="aboutAvior grayscale">
				<span class="topPointer show">QUALITY POLICY</span>
				<?=$this->displayImage('5'); ?>
			</a>
			<a href="/about-us/business-ethics" class="aboutAvior grayscale">
				<span class="topPointer show">BUSINESS ETHICS</span>
				<?=$this->displayImage('6'); ?>
			</a>
			<a href="/about-us/mcl-2006" class="aboutAvior grayscale last">
				<span class="topPointer show">MLC-2006</span>
				<?=$this->displayImage('7'); ?>
			</a>
		</div>
	</div>
</div>