	<div class="topInnerBanner">
		<h1 class="pageHeading">Contact</h1>
	</div>
<div id="<?=routes::getInstance()->getCurrentTopLevelPageID();?>_content_wrapper">
	<div class="contactUsWrapper clearfix">
		<div class="fleft leftContent">
			<div class="headOffice mBl">
				<?=$this->displayElement('head_office_editor');?>
				<a href="mailto:edna.ranara@aviormarine.com">edna.ranara@aviormarine.com</a>
			</div>
			<div class="branchOffice">
				<?=$this->displayElement('brach_office_editor'); ?>
				<a href="mailto:jes.agbayani@aviormarine.com">jes.agbayani@aviormarine.com</a>
			</div>
		</div>
		<div class="fright rightContent">
			<h2>Get in touch with us</h2>
			<p>For inquiries, please fill up the form below</p>
			<form action="POST" class="contactForm" enctype="multipart/form-data">
				<div class="clearfix row">
					<input type="text" name="name" placeholder="Name*" value="Name*"/>
				</div>
				<div class="clearfix row">
					<input type="text" name="company" placeholder="Company / Occupation"/>
				</div>
				<div class="clearfix row">
					<input type="text" name="telephone" placeholder="Telephone*"/>
				</div>
				<div class="clearfix row">
					<input type="email" name="email" placeholder="Email*"/>
				</div>
				<div class="clearfix row">
					<input type="text" name="address" placeholder="Address"/>
				</div>
				<div class="clearfix row">
					<select name="typeInquiry">
						<option value="">Type of Inquiry</option>
						<option value="Crew Management">CREW MANAGEMENT</option>
						<option value="Ship Management">SHIP MANAGEMENT</option>
						<option value="Outsourcing">OUTSOURCING</option>
						<option value="Management">MANAGEMENT</option>
						<option value="Complaint">COMPLAINT</option>
						<option value="Appication">APPLICATION</option>
						<option value="Others">OTHERS</option>
					</select>
				</div>
				<div class="clearfix row">
					<textarea name="inquiry"></textarea>
				</div>
				<div class="clearfix row">
				<input type="submit" value="submit" class="fright"/>
				</div>
			</form>
		</div>
	</div>
</div>