<div class="popupDialog product_dialog addCategory_popUp">
<h3><img src="/Project/Design/2_Enterprise/Applications/Products/Main_App_Layout/images/plus.png" />Create New Category</h3>
	<div class="subCategory_entity">
		<form method="POST" action="/<?=routes::getInstance()->getCurrentTopLevelURLName()?>/category/add">
			<div class="mBl">
				<strong>Category Title</strong><input class="validate[required,maxlength[45]] fright subCategory_entityTitle" type="text" name="title" maxlength="45">
			</div>
			<div>
				<strong>Url</strong><input class="fright subCategory_entityDescription" name="category_url" disabled="disabled"/>
			</div>
			<div id="button_container" class="fright mRs mBs mTs">
				<input type="submit" class="sprite fleft mRs mTs" name="add_category" value=" ">
				<span class="sprite mTs fleft pointer cancel" title="cancel"></span>
			</div>
		</form>
	</div>
</div>