<h2 class="mLxl innerPageHeading">LINKS</h2>
<ul class="mBxxl">
	<?php foreach($this->_get('link_nav_listing') as $nav):?>
		<li><a href="/links-and-downloads/view/<?=$nav->__get('permalink')?>"> <?=$nav->__get('product_title')?></a> </li>
	<?php endforeach?>
</ul>

<h2 class="mLxl innerPageHeading">DOWNLOADS</h2>
<ul class="mBxxl">
	<li><a href="/links-and-downloads/view/downloadables">Click to view all Downloads</a> </li>
</ul>