	<div class="topInnerBanner">
		<h1 class="pageHeading">Links and Downloads</h1>
	</div>
<div id="<?=routes::getInstance()->getCurrentTopLevelPageID();?>_content_wrapper">
	<div class="clearfix">
		<div class="fleft topicListWrap">
			%%LINKS_LIST%%
		</div>
		<div class="fright topicDetailsWrap">
		<?php if($this->_get('article_details')):?>
			<h2 class="innerPageHeading"><?=$this->_get('article_details')->__get('product_title')?></h2>
			<?=$this->_get('article_details')->__get('url_name')?>
		<?php else:?>
			<h2 class="innerPageHeading">DOWNLOADABLE FILES</h2>
			<?php foreach($this->_get('array_of_downloadables') as $downloadables):?>
					<a href="/links-and-downloads/viewDownloadables/file_id/<?=$downloadables->__get('pdf_id')?>"><?=$downloadables->__get('filename')?> </a>	<br />
			<?php endforeach?>
		<?php endif?>
		</div>
	</div>
</div>