	<div class="topInnerBanner">
		<h1 class="pageHeading">Seafarers</h1>
	</div>
<div id="<?=routes::getInstance()->getCurrentTopLevelPageID();?>_content_wrapper">
	<div class="clearfix">
		<div class="fleft topicListWrap">
			%%TOPIC_LIST%%
		</div>
		<div class="fright topicDetailsWrap clearfix mBxxl" itemscope itemtype="http://schema.org/Article">
			<h2 class="innerPageHeading" itemprop="name"><?=$this->_get('article_details')->__get('article_title')?></h2>
			<div itemprop="articleBody"><?=$this->_get('article_details')->__get('intro')?></div>
		</div>
	</div>
</div>