<header id="header" class="clearfix">
	<section class="clearfix">
		<div id='logo-holder' class="fleft">
				<h1 class="fleft"><a href="/"><img src="/Project/Design/1_Website/Panels/header/images/avior-logo.png" alt="Avior Marine Inc" title="We develop and maintain a dedicated pool of Seafarers"></a></h1>
		</div>
		<nav class="clearfix fright"><?= navigation::displayNavigationForPages('primary','home');?></nav>
	</section>
</header>