<form method="post" id="quick_apply_from" action="">
	Full Name <input type="text" name="full_name" /> <br />
	Rank(Position) <input type="text" name="rank" /> <br />
	Date of Birth <input type="text" name="date_of_birth" /> <br />
	Phone <input type="text" name="phone" /> <br />
	Email <input type="text" name="email" /> <br />
	Vessel Type <input type="text" name="vessel_type" /> <br />
	Comment <textarea name="comment"></textarea> <br />
	<input type="submit" name="mail" value="submit"  />
</form>