<div>
	<div id="users_online" class="fleft">
		<div id="userOnline_header"><span class="fc_starfish_gray5 fwB fs-xxl txt_shadow">Users Online</span></div>
		<div id="userOnine_content">
			<table>
				<tr>
					<td><span class="fc_starfish_gray4 fwB fs-xl">Total Users</span></td>
					<td class="fc_starfish_gray3 fs-xm fwB align_r"><span class="fc_starfish_blue">58</span> Online<td>
				</tr>
				<tr>
					<td><span class="fc_starfish_gray4 fwB fs-xl">Job Seeker</span></td>
					<td class="fc_starfish_gray3 fs-xm fwB align_r"><span class="fc_starfish_blue">36</span> Online<td>
				</tr>
				<tr>
					<td><span class="fc_starfish_gray4 fwB fs-xl">Employer</span></td>
					<td class="fc_starfish_gray3 fs-xm fwB align_r"><span class="fc_starfish_blue">22</span> Online<td>
				</tr>
			</table>
		</div>
	</div>

	<div id="registered_users" class="fright">
		<div id="registeredUsers_header"><span class="fc_starfish_gray5 fwB fs-xxl txt_shadow">Registered Users: 9</span></div>
		
		<div id="registeredUsers_content" class="fleft">
			<div id="content_header"><span class="fc_starfish_gray6 fwB fs-xl">Jobseeker</span></div>
			<div class="pHxs">
				<table class="fc_starfish_gray3 fwB fs-l">
					<tr>
						<td></td>
						<td class="align_c">Active</td>
						<td class="align_c">Not Active</td>
						<td class="align_c">Total</td>
					</tr>
					<tr>
						<td>Today</td>
						<td class="align_c"><span class="fc_starfish_blue">36</span></td>
						<td class="align_c"><span class="fc_starfish_blue">5</span></td>
						<td class="align_c"><span class="fc_starfish_green1">41</span></td>
					</tr>
					<tr>
						<td>This week</td>
						<td class="align_c"><span class="fc_starfish_blue">78</span></td>
						<td class="align_c"><span class="fc_starfish_blue">8</span></td>
						<td class="align_c"><span class="fc_starfish_green1">86</span></td>
					</tr>
					<tr>
						<td>This month</td>
						<td class="align_c"><span class="fc_starfish_blue">101</span></td>
						<td class="align_c"><span class="fc_starfish_blue">12</span></td>
						<td class="align_c"><span class="fc_starfish_green1">113</span></td>
					</tr>
					<tr>
						<td class="fc_starfish_gray4">Total</td>
						<td class="align_c"><span class="fc_starfish_green1">215</span></td>
						<td class="align_c"><span class="fc_starfish_green1">25</span></td>
						<td class="align_c"></td>
					</tr>
				</table>
			</div>
		</div>
		
		
		<div id="registeredUsers_content" class="fleft">
			<div id="content_header"><span class="fc_starfish_gray6 fwB fs-xl">Employers</span></div>
			<div class="pHxs">
				<table class="fc_starfish_gray3 fwB fs-l">
					<tr>
						<td></td>
						<td class="align_c">Active</td>
						<td class="align_c">Not Active</td>
						<td class="align_c">Total</td>
					</tr>
					<tr>
						<td>Today</td>
						<td class="align_c"><span class="fc_starfish_blue">36</span></td>
						<td class="align_c"><span class="fc_starfish_blue">5</span></td>
						<td class="align_c"><span class="fc_starfish_green1">41</span></td>
					</tr>
					<tr>
						<td>This week</td>
						<td class="align_c"><span class="fc_starfish_blue">78</span></td>
						<td class="align_c"><span class="fc_starfish_blue">8</span></td>
						<td class="align_c"><span class="fc_starfish_green1">86</span></td>
					</tr>
					<tr>
						<td>This month</td>
						<td class="align_c"><span class="fc_starfish_blue">101</span></td>
						<td class="align_c"><span class="fc_starfish_blue">12</span></td>
						<td class="align_c"><span class="fc_starfish_green1">113</span></td>
					</tr>
					<tr>
						<td class="fc_starfish_gray4">Total</td>
						<td class="align_c"><span class="fc_starfish_green1">215</span></td>
						<td class="align_c"><span class="fc_starfish_green1">25</span></td>
						<td class="align_c"></td>
					</tr>
				</table>
			</div>
		</div>
		
	</div>

</div>