<div>
	<div id="payments" class="fleft">
		<div id="payments_header"><span class="fc_starfish_gray5 fwB fs-xxl txt_shadow">Payments</span></div>
		<div id="payments_content">
			<table class="fc_starfish_gray3 fwB fs-l">
					<tr>
						<td></td>
						<td class="align_c">Active</td>
						<td class="align_c">Not Active</td>
						<td class="align_c">Total</td>
					</tr>
					<tr>
						<td>Today</td>
						<td class="align_c"><span class="fc_starfish_blue">36</span></td>
						<td class="align_c"><span class="fc_starfish_blue">5</span></td>
						<td class="align_c"><span class="fc_starfish_green1">41</span></td>
					</tr>
					<tr>
						<td>This week</td>
						<td class="align_c"><span class="fc_starfish_blue">78</span></td>
						<td class="align_c"><span class="fc_starfish_blue">8</span></td>
						<td class="align_c"><span class="fc_starfish_green1">86</span></td>
					</tr>
					<tr>
						<td>This month</td>
						<td class="align_c"><span class="fc_starfish_blue">101</span></td>
						<td class="align_c"><span class="fc_starfish_blue">12</span></td>
						<td class="align_c"><span class="fc_starfish_green1">113</span></td>
					</tr>
					<tr>
						<td class="fc_starfish_gray4">Total</td>
						<td class="align_c"><span class="fc_starfish_green1">215</span></td>
						<td class="align_c"><span class="fc_starfish_green1">25</span></td>
						<td class="align_c"></td>
					</tr>
				</table>
		</div>
	</div>

	<div id="registered_users" class="fright">
		<div id="registeredUsers_header"><span class="fc_starfish_gray5 fwB fs-xxl txt_shadow">Postings: 11</span></div>
		
		<div id="registeredUsers_content" class="fleft">
			<div id="content_header"><span class="fc_starfish_gray6 fwB fs-xl">Job</span></div>
			<div class="pHxs">
				<table class="fc_starfish_gray3 fwB fs-l">
					<tr>
						<td></td>
						<td class="align_c">Active</td>
						<td class="align_c">Not Active</td>
						<td class="align_c">Total</td>
					</tr>
					<tr>
						<td>Today</td>
						<td class="align_c"><span class="fc_starfish_blue">36</span></td>
						<td class="align_c"><span class="fc_starfish_blue">5</span></td>
						<td class="align_c"><span class="fc_starfish_green1">41</span></td>
					</tr>
					<tr>
						<td>This week</td>
						<td class="align_c"><span class="fc_starfish_blue">78</span></td>
						<td class="align_c"><span class="fc_starfish_blue">8</span></td>
						<td class="align_c"><span class="fc_starfish_green1">86</span></td>
					</tr>
					<tr>
						<td>This month</td>
						<td class="align_c"><span class="fc_starfish_blue">101</span></td>
						<td class="align_c"><span class="fc_starfish_blue">12</span></td>
						<td class="align_c"><span class="fc_starfish_green1">113</span></td>
					</tr>
					<tr>
						<td class="fc_starfish_gray4">Total</td>
						<td class="align_c"><span class="fc_starfish_green1">215</span></td>
						<td class="align_c"><span class="fc_starfish_green1">25</span></td>
						<td class="align_c"></td>
					</tr>
				</table>
			</div>
		</div>
		
		
		<div id="registeredUsers_content" class="fleft">
			<div id="content_header"><span class="fc_starfish_gray6 fwB fs-xl">Resume</span></div>
			<div class="pHxs">
				<table class="fc_starfish_gray3 fwB fs-l">
					<tr>
						<td></td>
						<td class="align_c">Active</td>
						<td class="align_c">Not Active</td>
						<td class="align_c">Total</td>
					</tr>
					<tr>
						<td>Today</td>
						<td class="align_c"><span class="fc_starfish_blue">36</span></td>
						<td class="align_c"><span class="fc_starfish_blue">5</span></td>
						<td class="align_c"><span class="fc_starfish_green1">41</span></td>
					</tr>
					<tr>
						<td>This week</td>
						<td class="align_c"><span class="fc_starfish_blue">78</span></td>
						<td class="align_c"><span class="fc_starfish_blue">8</span></td>
						<td class="align_c"><span class="fc_starfish_green1">86</span></td>
					</tr>
					<tr>
						<td>This month</td>
						<td class="align_c"><span class="fc_starfish_blue">101</span></td>
						<td class="align_c"><span class="fc_starfish_blue">12</span></td>
						<td class="align_c"><span class="fc_starfish_green1">113</span></td>
					</tr>
					<tr>
						<td class="fc_starfish_gray4">Total</td>
						<td class="align_c"><span class="fc_starfish_green1">215</span></td>
						<td class="align_c"><span class="fc_starfish_green1">25</span></td>
						<td class="align_c"></td>
					</tr>
				</table>
			</div>
		</div>
		
	</div>

</div>