<!--**************************************
				SCRIPT LINKS
    **************************************-->
<script src="Project/Design/1_Website/Main_Layout/scripts/cufon_yui.js" type="text/javascript"></script>
<script src="Project/Design/1_Website/Main_Layout/scripts/cufon.js" type="text/javascript"></script>
<script src="Project/Design/1_Website/Main_Layout/scripts/JQueryCorner_plugin.js" type="text/javascript"></script>

<!-- Pulled from http://code.google.com/p/html5shiv/ -->
<!--[if lt IE 9]>
<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
