<link rel="stylesheet" href="/Project/Design/2_Enterprise/Applications/_Common/css/common.css" type="text/css" media="screen" />
<link media="screen" rel="stylesheet" href="/Project/Design/2_Enterprise/Main_Layout/plugins/CKEditor/contents.css"/>
<script src="/Project/Design/2_Enterprise/Applications/_Common/templates/inpage_javascript.js"></script>
<script type="text/javascript" src="/Project/Design/2_Enterprise/Main_Layout/scripts/xhtml.js"></script>
<script src="/Project/Design/2_Enterprise/Main_Layout/plugins/CKEditor/ckeditor.js"></script>