<div id="<?=routes::getInstance()->getCurrentTopLevelPageID();?>_content_wrapper" class="clearfix">
	<div class="topSection clearfix">
		<div class="fleft">
			<div>
				<?=$this->displayElement('slider_text_editor')?>
				<a href="/about-us" id="readMoreButton" class="fright">read more</a>				
			</div>
			<ul class="unstyled" id="slider">
				<?$i=0;?>
				<?foreach ($this->_XMLObj->slider->image_id as $image):?><!-- counts all image nodes present inside the slider tag -->
					<?if($this->displayBackgroundImage($i)):?><!-- displays the image  if image_id != 0 -->
						<li <?=$this->displayBackgroundImage($i); $active = ($i == 0) ? "class='active'" : ''; echo $active?>>
						</li>
					<?endif;?>
					<?$i++;?>
				<?endforeach;?>
			</ul>
		</div>
		<div class="fright">
			<aside class="grayscale" <?=$this->displayBackgroundImage(4)?>)"><a href="/seafarers"></a><h1 class="ArvilSans">SEAFARERS</h1></aside>
			<aside class="grayscale" <?=$this->displayBackgroundImage(5)?>><a href="/careers"></a><h1 class="ArvilSans">APPLY</h1></aside>
		</div>
	</div>
	<div class="bottomSection clearfix">
		<aside class="grayscale" <?=$this->displayBackgroundImage(6)?>)"><a href="/news"></a><h1 class="ArvilSans">LATEST NEWS</h1></aside>
		<aside class="grayscale" <?=$this->displayBackgroundImage(7)?>)"><a href="/gallery"></a><h1 class="ArvilSans">GALLERY</h1></aside>
		<aside class="grayscale" <?=$this->displayBackgroundImage(8)?>)"><a href="/about-us/fleet-manned"></a><h1 class="ArvilSans">FLEET MANNED</h1></aside>
	</div>
</div>