	<div class="topInnerBanner">
		<h1 class="pageHeading">Corporate Social Responsibility</h1>
	</div>
<div id="<?=routes::getInstance()->getCurrentTopLevelPageID();?>_content_wrapper">
	<div class="clearfix">
		<div class="fleft topicListWrap">
			%%TOPIC_LIST%%
		</div>
		<div class="fright topicDetailsWrap">
			<h2 class="innerPageHeading"><?=$this->_get('article_details')->__get('article_title')?></h2>
			<?=$this->_get('article_details')->__get('intro')?>
		</div>
	</div>
</div>