	<div class="topInnerBanner">
		<h1 class="pageHeading">Gallery</h1>
	</div>
<div id="<?=routes::getInstance()->getCurrentTopLevelPageID();?>_content_wrapper">
	<div class="albumImageWrap">
		<div class="clearfix mVxl">
			<a href="/gallery" class="fwB">< back to Gallery</a>
			<h2><?=$this->_get('album_title')?></h2>
			
		</div>	
		<ul class="imageListing">
		<? foreach($this->_get('array_of_images') as $image) { ?>	
			<li>
				<a class="fancybox-button" rel="fancybox-button" href="/Data/Images/<?=$image->__get('full_path'); ?>" title="">
					<span class="albumImage show" style="background-image:url('/Data/Images/<?=$image->__get('full_path'); ?>');"></span>
				</a>
			</li>
		<? } ?>	
		</ul>
		
		<?if($this->getNumberOfPages() > 1):?>		
		%%PAGINATION%%
		<?endif;?>
	</div>	
</div>	