	<div class="topInnerBanner">
		<h1 class="pageHeading">Gallery</h1>
	</div>
<div id="<?=routes::getInstance()->getCurrentTopLevelPageID();?>_content_wrapper">
	<div class="galleryListTopWrap pTxl">
		<p class="galleryText mBxl">
			<?=$this->displayElement('page_content_editor'); ?>
		</p>
		<ul class="galleryListing">
		<? if(count($this->_get('array_of_albums')) > 0) { ?>	
		<?$count = 1; ?>
		
			<? foreach($this->_get('array_of_albums') as $album) { ?>
				<li id="<?=$count?>" >
					<? 
						$image_preview	= $album->__get('image_preview');
						$size_preview	= $album->__get('size_preview');
					?>					
					<a href="/gallery/<?=$album->__get('permalink');?>" class="">
						<span class="show albumImage" style="background-image:url(/Data/Images/<?=$album->__get('album_folder')?>/<?=$size_preview->__get('dimensions')?>_thumb/<?=$image_preview->__get('filename')?><?=$album->__get('image_extension');?>)"></span>
						<span class="albumTitle" value=""><?=$album->__get('album_title');?></span>
					</a>
				</li>
				
			<?$count++;?>	
			<? } ?>	
		<? } else { ?>
			
		<? } ?>
		</ul> 
	</div>
</div>